[package]
name = "keyani"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.7.0", features = ["image", "tokio"] }
iced_native = "0.8.0"
rand = "0.8.5"
